### ISSUE TITLE
Module is not truly disabled when turned off

### ISSUE THREAD

**Issue by grantkemp** [BlueAcornInc/UniversalAnalytics#18]
Even if I don't have the universal analytics switched on in the magento backend, it still seems to be injecting changes into the frontend and causing errors. 

The expected behaviour is that if its disabled in the magento backend under the Google APi setting , then it is not making changes.

**Comment by Skrath** [comment]
I've got another dev confirming this on my end, will have to take a look.

**Comment by lapty** [comment]
@grantkemp I am able to turn the module through the backend off and on as intended - after I clear my cache or if caching is disabled. Could you try disabling the module then clearing cache to see if it is properly disabled?

**Comment by mystix** [comment]
Found quite a number of loose ends contributing to this bug:

* The config `baua/settings/enabled` in `config.xml` is never used because in `system.xml`, the actual config used is `google/baua/active`.
* The config `google/baua/active`, if enabled, is only used to turn off legacy ga.js (see universalanalytics.xml layout file) -- it doesn't stop the injection of universal analytics changes into the frontend
* `BlueAcorn_UniversalAnalytics_Helper_Data#isActive()` is never called in any of the event observers registered in `config.xml`, so all UA observers continue doing their work in the background without regard for whether the extension is enabled

**Comment by twslade** [comment]
Thanks again @mystix
